"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import AppShell from "@/components/AppShell";
import SearchInput from "@/components/SearchInput";
import { Plus } from "lucide-react";
import { useLanguage } from "@/lib/i18n";

export default function TransactionsPage() {
  const { lang, t } = useLanguage();
  const [transactions, setTransactions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [search, setSearch] = useState("");

  async function load(status?: string, searchValue?: string) {
    setLoading(true);
    try {
      const params: Record<string, string> = {};
      if (status) params.payment_status = status;
      if (searchValue) params.search = searchValue;
      const res = await api.getTransactions(Object.keys(params).length ? params : undefined);
      setTransactions(res.transactions.data || res.transactions);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  useEffect(() => {
    const timer = setTimeout(() => load(statusFilter || undefined, search || undefined), 300);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [search]);

  function handleFilter(status: string) {
    setStatusFilter(status);
    load(status || undefined, search || undefined);
  }

  return (
    <AppShell
      title={t("transactions")}
      subtitle={lang === "ar" ? "سجلات الإرسال والاستلام" : "Send and receive records"}
      actions={
        <Link href="/transactions/new">
          <button className="btn flex items-center gap-1.5">
            <Plus size={16} strokeWidth={2.5} /> {lang === "ar" ? "جديد" : "New"}
          </button>
        </Link>
      }
    >
      <SearchInput value={search} onChange={setSearch} placeholder={lang === "ar" ? "بحث بالعميل أو المستلم أو المرجع..." : "Search by customer, receiver, or reference..."} />

      <div className="flex gap-2 mb-6">
        {["", "pending", "completed"].map((s) => (
          <button
            key={s}
            onClick={() => handleFilter(s)}
            className={statusFilter === s ? "btn" : "btn-ghost"}
          >
            {s === "" ? (lang === "ar" ? "الكل" : "All") : lang === "ar" ? (s === "pending" ? "معلقة" : "مكتملة") : s[0].toUpperCase() + s.slice(1)}
          </button>
        ))}
      </div>

      {error && <p className="text-red-600 text-sm mb-4">{error}</p>}
      {loading ? (
        <p className="text-slate-400 text-sm">{t("loading")}</p>
      ) : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>{lang === "ar" ? "المرجع" : "Ref"}</th>
                <th>{t("customer")}</th>
                <th>{lang === "ar" ? "الممر" : "Corridor"}</th>
                <th>{t("amount")}</th>
                <th>{lang === "ar" ? "الإجمالي" : "Total"}</th>
                <th>{lang === "ar" ? "أنشئت بواسطة" : "Generated by"}</th>
                <th>{lang === "ar" ? "المالك" : "Owner"}</th>
                <th>{t("status")}</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {transactions.map((tx) => (
                <tr key={tx.id}>
                  <td className="font-mono text-xs">{tx.tranx_ref}</td>
                  <td>{tx.customer_name}</td>
                  <td>{tx.country1?.country || "—"} &rarr; {tx.country2?.country || "—"}</td>
                  <td>{tx.amount}</td>
                  <td>{tx.total}</td>
                  <td>{tx.created_by?.name}</td>
                  <td>{tx.owner?.name || "—"}</td>
                  <td><span className={`badge badge-${tx.payment_status?.replace(" ", "-")}`}>{tx.payment_status}</span></td>
                  <td>
                    <Link href={`/transactions/${tx.id}`} className="font-semibold">{lang === "ar" ? "عرض" : "View"}</Link>
                  </td>
                </tr>
              ))}
              {transactions.length === 0 && (
                <tr><td colSpan={9} className="text-center text-slate-400 py-8">{lang === "ar" ? "لا توجد معاملات بعد." : "No transactions yet."}</td></tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </AppShell>
  );
}
