"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api } from "@/lib/api";
import ReceiptActions from "@/components/ReceiptActions";

export default function PaymentReceiptPage() {
  const params = useParams();
  const id = Number(params.id);
  const [payment, setPayment] = useState<any>(null);
  const [isExpense, setIsExpense] = useState(false);
  const [isChad, setIsChad] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    api
      .getPaymentReceiptData(id)
      .then((res) => {
        setPayment(res.payment);
        setIsExpense(res.is_expense);
        setIsChad(res.is_chad);
      })
      .catch((err) => setError(err.message));
  }, [id]);

  if (error) return <div className="min-h-screen flex items-center justify-center text-red-600 text-sm">{error}</div>;
  if (!payment) return <div className="min-h-screen flex items-center justify-center text-slate-400 text-sm">Loading...</div>;

  const amount = Math.abs(Number(payment.amount));

  return (
    <div className="min-h-screen bg-slate-100 flex flex-col items-center py-10 px-4 gap-5">
      <div id="receipt-card" className="bg-white rounded-2xl shadow-lg w-full max-w-md p-6" style={{ fontFamily: "system-ui, sans-serif" }}>
        <div className="flex items-start justify-between border-b border-slate-100 pb-4 mb-4">
          <div>
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-teal-500 to-teal-700 flex items-center justify-center text-white font-bold text-sm mb-2">ES</div>
            <h1 className="text-lg font-bold text-slate-900">EasyService</h1>
            <p className="text-xs text-slate-400">{isExpense ? "Customer Expenses (Debit) Receipt" : "Customer Funding Receipt"}</p>
          </div>
          <div className="text-right">
            <p className="font-mono text-sm font-bold">#{payment.id}</p>
            <p className="text-xs text-slate-400">{new Date(payment.created_at).toLocaleString()}</p>
          </div>
        </div>

        {[
          ["Customer", payment.customer_name],
          ["Country", payment.location || "—"],
          ["Currency", payment.currency_code],
          ["Staff", payment.staff_name],
          ["Staff country", payment.staff_location || "—"],
        ].map(([label, value]) => (
          <div key={label} className="flex justify-between py-1.5 text-sm border-b border-slate-50">
            <span className="text-slate-500">{label}</span>
            <strong className="text-slate-900">{value}</strong>
          </div>
        ))}

        <div className="flex justify-between py-2.5 mt-2 px-3 rounded-lg bg-amber-50 text-sm">
          <span className="font-semibold text-red-700">{isExpense ? "Debit amount" : "Funding amount"}</span>
          <strong className="text-red-700">{payment.currency_symbol} {amount.toLocaleString()}</strong>
        </div>
        {isChad && (
          <div className="flex justify-between py-2.5 mt-1.5 px-3 rounded-lg bg-amber-50 text-sm">
            <span className="font-semibold text-red-700">Divided amount</span>
            <strong className="text-red-700">{payment.currency_symbol} {(amount / 5).toLocaleString()}</strong>
          </div>
        )}

        <div className="flex justify-between py-2 mt-3 text-sm">
          <span className="text-slate-500">Wallet balance</span>
          <strong className="text-red-700">{payment.currency_symbol} {Number(payment.customer_balance).toLocaleString()}</strong>
        </div>
        {isChad && (
          <div className="flex justify-between py-2 text-sm">
            <span className="text-slate-500">Divided wallet balance</span>
            <strong className="text-red-700">{payment.currency_symbol} {(Number(payment.customer_balance) / 5).toLocaleString()}</strong>
          </div>
        )}

        {payment.remark && (
          <p className="text-xs text-slate-400 italic mt-3">Note: {payment.remark}</p>
        )}

        <p className="text-center font-semibold text-sm text-teal-700 mt-4">
          {isExpense ? "Account successfully debited!" : "Customer successfully funded!"}
        </p>

        <p className="text-center text-[11px] text-slate-400 mt-4 pt-4 border-t border-slate-100">
          Generated by {payment.staff_name?.toUpperCase()} — EasyService
        </p>
      </div>

      <div className="w-full max-w-md">
        <ReceiptActions
          targetId="receipt-card"
          filename={`${isExpense ? "expense" : "funding"}-${payment.id}.png`}
          shareTitle={`Receipt #${payment.id}`}
        />
      </div>
    </div>
  );
}
