"use client";

const CHAD_OFFICES: Record<string, string[]> = {
  Ndjamena: ["90850808", "68666611"],
  Abeche: ["66230611", "99281685"],
  Moundou: ["66241234", "99345678"],
  Sarh: ["66251111", "99362222"],
  Kelo: ["66263333"],
  Koumra: ["66274444", "99385555"],
  Pala: ["66285678"],
  "Am Timan": ["66296789", "99407890"],
  Mongo: ["66307891", "99418902"],
  "Faya-Largeau": ["66318903"],
  "Goz Beida": ["66329014", "99430125"],
  "Al Aradip": ["66340126"],
  Biltine: ["66351237", "99441238"],
  Kalayit: ["66362348"],
  Massaguet: ["66373459", "99452460"],
  "Am Hadjar": ["66384560"],
  Bitkine: ["66395671", "99463672"],
  Abdi: ["66406782"],
  Arada: ["66417893", "99474894"],
};

export default function TransactionReceiptCard({ transaction }: { transaction: any }) {
  const completed = transaction.payment_status === "completed";

  return (
    <div id="receipt-card" className="bg-white rounded-2xl shadow-lg w-full p-6" style={{ fontFamily: "system-ui, sans-serif" }}>
      {transaction.paid_via_partner === "nita" && (
        <div className="bg-amber-500 text-white text-center text-xs font-bold uppercase tracking-wide py-1.5 rounded-lg mb-4">
          NITA
        </div>
      )}
      <div className="flex items-start justify-between border-b border-slate-100 pb-4 mb-4">
        <div>
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-teal-500 to-teal-700 flex items-center justify-center text-white font-bold text-sm mb-2">ES</div>
          <h1 className="text-lg font-bold text-slate-900">EasyService</h1>
          <p className="text-xs text-slate-400">Transaction Receipt</p>
        </div>
        <div className="text-right">
          <p className="font-mono text-sm font-bold">{transaction.tranx_ref}</p>
          <p className="text-xs text-slate-400">{new Date(transaction.created_at).toLocaleString()}</p>
          <span className={`inline-block mt-1 px-2.5 py-1 rounded-full text-[11px] font-bold ${completed ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>
            {completed ? "COMPLETED" : "PENDING"}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3 text-sm mb-4">
        <div>
          <div className="text-[11px] font-semibold uppercase text-slate-400">Sender</div>
          <div className="font-medium">{transaction.customer_name}</div>
          <div className="text-xs text-slate-400">{transaction.country_code} {transaction.phone}</div>
        </div>
        {transaction.receiver_name && (
          <div>
            <div className="text-[11px] font-semibold uppercase text-slate-400">Receiver</div>
            <div className="font-medium">{transaction.receiver_name}</div>
            <div className="text-xs text-slate-400">{transaction.receiver_phone}</div>
          </div>
        )}
      </div>

      {[
        ["Sending country", `${transaction.country1?.country || "—"} (${transaction.country1?.currency_code || ""})`],
        ["Receiving country", `${transaction.country2?.country || "—"} (${transaction.country2?.currency_code || ""})`],
        ["Amount sent", Number(transaction.amount).toLocaleString()],
        ["Rate applied", transaction.rate],
        ["Amount receiver gets", Number(transaction.total).toLocaleString()],
        ["Advance paid", Number(transaction.advance).toLocaleString()],
        ["Generated by", transaction.created_by?.name || "—"],
        ["Owner (invoice belongs to)", transaction.owner?.name || transaction.created_by?.name || "—"],
      ].map(([label, value]) => (
        <div key={label} className="flex justify-between py-1.5 text-sm border-b border-slate-50">
          <span className="text-slate-500">{label}</span>
          <strong className="text-slate-900">{value}</strong>
        </div>
      ))}
      <div className="flex justify-between py-2 text-sm mt-1">
        <span className="font-bold text-slate-900">Current customer balance</span>
        <strong className="text-teal-700">{transaction.customer_balance !== null && transaction.customer_balance !== undefined ? Number(transaction.customer_balance).toLocaleString() : "—"}</strong>
      </div>

      {transaction.country2?.country?.trim().toLowerCase() === "chad" && (
        <>
          <div className="flex justify-between py-2.5 mt-2 px-3 rounded-lg bg-amber-50 text-sm">
            <span className="font-semibold text-red-700">Divided amount</span>
            <strong className="text-red-700">{(Number(transaction.total) / 5).toLocaleString()}</strong>
          </div>
          {transaction.chad_region && CHAD_OFFICES[transaction.chad_region] && (
            <div className="flex justify-between py-2 text-sm mt-1">
              <span className="text-slate-500">☎ Office ({transaction.chad_region})</span>
              <span className="text-right">
                <strong className="text-red-700 text-xs">{CHAD_OFFICES[transaction.chad_region].join(" / ")}</strong>
                <span className="block text-[10px] text-slate-400 italic">09:00 – 17:00</span>
              </span>
            </div>
          )}
        </>
      )}

      {transaction.notes && (
        <p className="text-xs text-slate-400 italic mt-3">Note: {transaction.notes}</p>
      )}

      <p className="text-center text-[11px] text-slate-400 mt-6 pt-4 border-t border-slate-100">
        System-generated receipt — EasyService
      </p>
    </div>
  );
}
